### ISSUE TITLE
Support API tokens

### ISSUE THREAD

**Issue by mhalano** [CMB/cligh#9]
If you're using GitHub with 2FA you should use API tokens instead passwords to do operations (or request 2FA code, but this could be tricky).
I found this application because is added to Ubuntu repository and I think it needs some love because that.

**Comment by CMB** [comment]
The program only asks for a password when you generate the config file.
It uses the username and password to fetch an API token, and the token
is stored in the config file.
I suppose that if you were using 2FA you could perhaps pre-populate the
config file with a token?
But I don't know.
What else do we need to be doing?

**Comment by mhalano** [comment]
Theoretically I could use the token as the password. I do this on SSH. The problem is the cligh says it only supports basic authentication.

**Comment by CMB** [comment]
Yes, it uses basic authentication with the API token as the password.
And that's all in the library that it uses.
As I said, the only time it uses your actual GitHub password is when
you run cligh configure to generate the configuration file,
where it stores the username and the API token.

As far as I can tell, the only time it needs to send a request with a
one-time password is when creating an oauth token.
I could rework cligh configure so that it prompts for and uses your
one-time password when it creates the token, but from what I can tell,
this is all that would be needed to fully support 2FA.

**Comment by MetzDePro** [comment]
![8da5737bd35c492a65d9e2393243cde4979730d16d768c8401 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/23369221/20160041/0b451e86-a717-11e6-8293-29abfc3f2efe.jpg)

**Comment by MetzDePro** [comment]
![cae18d8dd585155d384a51a69afff6c78a9e9427a9c99abca8 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/23369221/20160070/3df62dc0-a717-11e6-8672-7e61d1cd4777.png)

**Comment by MetzDePro** [comment]
please give me the solution
